Fix build error caused by mkdocs (v1.5.0)
timvink/mkdocs-charts-plugin pull request #17
Opened 2023-07-28 01:51 UTC by mgao6767

Fix https://github.com/timvink/mkdocs-charts-plugin/issues/16#issue-1823961327 as suggested by mkdocs' release note:

> Breaking change: `config.extra_javascript` is no longer a plain list of strings, but instead a list of `ExtraScriptValue` items. So you can no longer treat the list values as strings. If you want to keep compatibility with old versions, just always reference the items as `str(item)` instead. And you can still append plain strings to the list if you wish.

2023-07-31 11:02 UTC, SH2282000 commented
I would rather write `list(map(str, config["extra_javascript"]))` instead of `[str(item) for item in config["extra_javascript"]]` as the same fn. is applied to all elements. 

This is a breaking change, would it be possible to review this M.R. A.S.A.P. ?

cc @timvink @mgao6767 @squidfunk

2023-07-31 13:21 UTC, squidfunk commented
I'm not sure why I was CC'd.

2023-08-03 16:49 UTC, oprypin requested changes
Sorry I think this isn't the best way to approach it because it strips every script item from its information *and writes it back*. I propose #18 instead

2023-08-03 21:21 UTC, closed without merging

2023-08-26 19:55 UTC, timvink commented
Thanks for the efforts @mgao6767 and @oprypin !